# Generated by Django 3.0.3 on 2020-05-13 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messagesend',
        ),
    ]
