# Generated by Django 3.0.3 on 2020-05-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0004_auto_20200513_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessage',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sendmessage',
            name='meme',
            field=models.ImageField(upload_to='meme_image'),
        ),
    ]
