# Generated by Django 3.0.3 on 2020-05-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0005_auto_20200513_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessage',
            name='meme',
            field=models.ImageField(blank=True, null=True, upload_to='meme_image'),
        ),
    ]
