# Generated by Django 3.0.3 on 2020-05-13 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0006_auto_20200513_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendmessage',
            name='meme',
        ),
    ]
