# Generated by Django 3.0.3 on 2020-05-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0008_auto_20200514_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmessage',
            name='meme',
            field=models.ImageField(blank=True, null=True, upload_to='meme_image'),
        ),
    ]
