# Generated by Django 3.0.3 on 2020-05-14 13:27

import basicapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0009_sendmessage_meme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessage',
            name='meme',
            field=models.ImageField(blank=True, null=True, upload_to='meme_image', validators=[basicapp.models.validate_image]),
        ),
    ]
