# Generated by Django 3.0.3 on 2020-05-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0010_auto_20200514_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessage',
            name='message',
            field=models.CharField(max_length=1500),
        ),
    ]
