# Generated by Django 3.0.3 on 2020-05-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0011_auto_20200514_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessage',
            name='message',
            field=models.TextField(max_length=1500),
        ),
    ]
