# Generated by Django 3.0.3 on 2020-05-14 18:20

import basicapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0012_auto_20200514_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessage',
            name='meme',
            field=models.ImageField(blank=True, null=True, upload_to='media', validators=[basicapp.models.validate_image]),
        ),
    ]
